### ISSUE TITLE
Model name

### ISSUE THREAD

**Issue by lukestanley** [luchris429/DiscoPOP#1]
Hi, project sounds quite interesting but I'm not sure running it is going to work since it looks like the model name of `gpt4_20231230_1106preview` is not correct:
https://github.com/luchris429/DiscoPOP/blob/c0e426698438014ea17592cb1c39e3be21c71d79/scripts/launch_evo.py#L15
Is this unused code?

**Comment by luchris429** [comment]
Apologies! That name is from our Azure endpoints, which we removed for the release. Will fix ASAP

**Comment by luchris429** [comment]
Should be fixed now!
